---
- name: first play - Build and Push Docker Image
  hosts: worker
  gather_facts: false
  become: yes
  tasks:
      # Task 1: Cleanup any existing code from the previous deployment
      - name: Remove old application code
        file:
          path: /home/ubuntu/ansiblejob  # Path to the directory where code is copied
          state: absent  # This will remove the directory and its contents
  tasks:
    # Task 2: Copy the application code to the worker node
    - name: Copy application code to the worker
      copy:
        src: /var/lib/jenkins/workspace/ABC-technologie-ansible-docker-k8s/ # Local path on your Ansible control node (Jenkins server)
        dest: /home/ubuntu/ansiblejob # Destination on the worker node

  # tasks:
  #   # Build Dockerfile
  #   - name: Build Docker Image
  #     community.docker.docker_image:
  #       path: .
  #       name: abc-technologie-app-ansible-docker-k8s
  #       tag: latest
  #       build: true

  #   # Push Docker image to Docker Hub
  #   - name: Push Docker Image to Docker Hub
  #     community.docker.docker_image:
  #       name: kassimabdi/abc-technologie-app-ansible-docker-k8s
  #       tag: latest
  #       push: yes
  #       source: build

# - name: second play - Deploy Artifact to Kubernetes
#   hosts: master
#   become: yes
#   tasks:
#     # Deploy Artifact in Kubernetes
#     - name: Deploy Artifact in Kubernetes
#       kubernetes.core.k8s:
#         state: present
#         definition: "{{ lookup('file', 'deployment.yml') }}"  
#     # setup service of the app
#     - name: Deploy Artifact in Kubernetes
#       kubernetes.core.k8s:
#         state: present
#         definition: "{{ lookup('file', 'service.yml') }}"  



