---
- name: second play - Deploy Artifact to Kubernetes
  hosts: localhost
  become: no
  tasks:
    - name : copy the deployment file to home/ubuntu
      copy:
          src: /var/lib/jenkins/workspace/ABC-technologie-ansible-docker-k8s-master-job/ deployment.yml# Local path on your Ansible control node (Jenkins server)
          dest: /home/ubuntu/ansiblejob
    # Deploy Artifact in Kubernetes && setup service of the app
    - name: Deploy Artifact in Kubernetes
      command: kubectl apply -f deployment.yml
       args:
          chdir: /home/ubuntu/ansiblejob
