---
- name: first play - Build and Push Docker Image
  hosts: worker
  gather_facts: false
  become: yes
  tasks:
    # Build Dockerfile
    - name: Build Docker Image
      community.docker.docker_image:
        path: .
        name: abc-technologie-app
        tag: latest
        build: true

    # Push Docker image to Docker Hub
    - name: Push Docker Image to Docker Hub
      community.docker.docker_image:
        name: kassimabdi/abc-technologie-app
        tag: latest
        push: yes
        source: build

# - name: second play - Deploy Artifact to Kubernetes
#   hosts: master
#   become: yes
#   tasks:
#     # Deploy Artifact in Kubernetes
#     - name: Deploy Artifact in Kubernetes
#       kubernetes.core.k8s:
#         state: present
#         definition: "{{ lookup('file', 'deployment.yml') }}"  
#     # setup service of the app
#     - name: Deploy Artifact in Kubernetes
#       kubernetes.core.k8s:
#         state: present
#         definition: "{{ lookup('file', 'service.yml') }}"  



