---
- name: second play - Deploy Artifact to Kubernetes
  hosts: master
  gather_facts: false
  become: yes
  tasks:
    # - name: Copy the deployment file to /home/ubuntu
    #   copy:
    #     src: /var/lib/jenkins/workspace/ABC-technologie-ansible-docker-k8s-master-job/deployment.yml # Correct the src path
    #     dest: /home/ubuntu/ansiblejob
    
    # - name: Deploy Artifact in Kubernetes
    #   kubernetes.core.k8s:
    #     state: present
    #     namespace: default  # Specify your Kubernetes namespace
    #     definition: "{{ lookup('file', 'deployment.yml') }}"
     
    - name: Create a Deployment by reading the definition from a local file 
      command: sudo kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f deployment.yml

    # - name: Deploy Artifact in Kubernetes
    #   command: kubectl apply -f deployment.yml
    #   args:
    #     chdir: /var/lib/jenkins/workspace/ABC-technologie-ansible-docker-k8s-master-job

