---
- name: second play - Deploy Artifact to Kubernetes
  hosts: localhost
  become: no
  tasks:
    - name: Copy the deployment file to /home/ubuntu
      copy:
        src: /var/lib/jenkins/workspace/ABC-technologie-ansible-docker-k8s-master-job/deployment.yml # Correct the src path
        dest: /home/ubuntu/ansiblejob

    - name: Deploy Artifact in Kubernetes
      command: kubectl apply -f deployment.yml
      args:
        chdir: /home/ubuntu/ansiblejob

