apiVersion: apps/v1
kind: Deployment
metadata:
  name: abctechnologies-deployment
  labels:
    app: abc-tech-app
spec:
  replicas: 2  # Two replicas of the application
  minReadySeconds: 45  # Pods should be ready for 45 seconds before considering them fully available
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # During updates, a maximum of one pod can be unavailable at a time
      maxSurge: 1  # Only one extra pod is created during an update
  selector:
    matchLabels:
      app: abc-tech-app  # Selects pods with this label
  template:
    metadata:
      labels:
        app: abc-tech-app  # Ensures the pods have this label
    spec:
      containers:
        - name: app-container  # Better naming for clarity
          image: kassimabdi/abc-technologie-app:latest  # Always pull the latest image for first-time deployment
          imagePullPolicy: Always  # Ensures that the latest image is always pulled
          ports:
            - containerPort: 8080  # Expose port 8080 for the application
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5  # Small delay before checking if the container is ready
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10  # Wait for the container to fully start before checking liveness
            periodSeconds: 20
