kind: Deployment
apiVersion: apps/v1
metadata:
  name: abctechnologies-deployment
spec:
  replicas: 2
  minReadySeconds: 45
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: abc-tech-app
  template:
    metadata:
      labels:
        app: abc-tech-app
    spec:
      containers:
        - name: app
          image: kassimabdi/abc-technologie-app-ansible-docker-k8s  # the image url
          ports:
            - containerPort: 8080  # Expose container port 8080

---
kind: Service
apiVersion: v1
metadata:
  name: abc-tech-service
spec:
  type: NodePort
  selector:
    app: abc-tech-app
  ports:
    - port: 80           # Cluster port
      targetPort: 8080   # Container port
      nodePort: 30007    # outside world port
